import { useState, useEffect } from "react";
import useEmblaCarousel from "embla-carousel-react";
import { motion, AnimatePresence } from "framer-motion";
import { X, ChevronLeft, ChevronRight, ZoomIn } from "lucide-react";

// Optimized data structure - uses base filenames
// The component expects .webp files generated by the optimization script
const galleryImages = [
    { id: 1, base: "art-1", alt: "Concept Art 1" },
    { id: 2, base: "art-2", alt: "Concept Art 2" },
    { id: 3, base: "art-3", alt: "Environment Design" },
    { id: 4, base: "art-4", alt: "Character Design" },
    { id: 5, base: "art-5", alt: "Mood Piece" },
    { id: 6, base: "art-6", alt: "Action Shot" },
];

export const GallerySection = () => {
    const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true, align: "center" });
    const [lightboxOpen, setLightboxOpen] = useState(false);
    const [lightboxIndex, setLightboxIndex] = useState(0);
    const [isPaused, setIsPaused] = useState(false);

    // Auto-play logic
    useEffect(() => {
        if (!emblaApi || isPaused || lightboxOpen) return;

        const interval = setInterval(() => {
            emblaApi.scrollNext();
        }, 2500);

        return () => clearInterval(interval);
    }, [emblaApi, isPaused, lightboxOpen]);

    // Keyboard navigation for carousel
    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (lightboxOpen) {
                if (e.key === "ArrowLeft") navigateLightbox(-1);
                if (e.key === "ArrowRight") navigateLightbox(1);
                if (e.key === "Escape") setLightboxOpen(false);
            } else if (emblaApi) {
                if (e.key === "ArrowLeft") emblaApi.scrollPrev();
                if (e.key === "ArrowRight") emblaApi.scrollNext();
            }
        };

        window.addEventListener("keydown", handleKeyDown);
        return () => window.removeEventListener("keydown", handleKeyDown);
    }, [emblaApi, lightboxOpen, lightboxIndex]);

    const openLightbox = (index: number) => {
        setLightboxIndex(index);
        setLightboxOpen(true);
        setIsPaused(true);
    };

    const closeLightbox = () => {
        setLightboxOpen(false);
        setIsPaused(false);
    };

    const navigateLightbox = (direction: number) => {
        let newIndex = lightboxIndex + direction;
        if (newIndex < 0) newIndex = galleryImages.length - 1;
        if (newIndex >= galleryImages.length) newIndex = 0;
        setLightboxIndex(newIndex);
    };

    return (
        <section
            className="py-24 bg-eclipse-black relative overflow-hidden"
            id="gallery-section"
            onMouseEnter={() => setIsPaused(true)}
            onMouseLeave={() => !lightboxOpen && setIsPaused(false)}
        >
            <div className="container mx-auto px-6 mb-12 text-center">
                <motion.h2
                    className="font-cinzel text-4xl md:text-5xl font-bold text-pure-white mb-4"
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                >
                    VISIONS DE L'ÉCLIPSE
                </motion.h2>
                <motion.div
                    className="h-1 w-24 bg-eclipse-gold mx-auto"
                    initial={{ scaleX: 0 }}
                    whileInView={{ scaleX: 1 }}
                    transition={{ duration: 0.8, delay: 0.2 }}
                />
            </div>

            {/* Carousel Container */}
            <div className="w-full max-w-[1400px] mx-auto px-4 md:px-12">
                <div className="overflow-hidden" ref={emblaRef}>
                    <div className="flex -ml-4">
                        {galleryImages.map((image, index) => (
                            <div
                                key={image.id}
                                className="flex-[0_0_85%] md:flex-[0_0_33.33%] min-w-0 pl-4 relative"
                            >
                                <motion.div
                                    className="relative aspect-[16/9] overflow-hidden rounded-lg group cursor-pointer border border-white/5 bg-eclipse-darker"
                                    initial={{ opacity: 0, scale: 0.9 }}
                                    whileInView={{ opacity: 1, scale: 1 }}
                                    transition={{ duration: 0.5, delay: index * 0.1 }}
                                    onClick={() => openLightbox(index)}
                                    whileHover={{ y: -5 }}
                                >
                                    <img
                                        src={`/assets/gallery/${image.base}_thumb.webp`}
                                        alt={image.alt}
                                        className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
                                        loading="lazy"
                                        onError={(e) => {
                                            // Fallback logic
                                            const target = e.currentTarget;
                                            const fallback = `/assets/gallery/${image.base}.jpg`;
                                            if (target.src !== window.location.origin + fallback) {
                                                target.src = fallback;
                                            }
                                        }}
                                    />

                                    {/* Reveal/Hover Overlay */}
                                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end justify-center pb-6">
                                        <span className="text-eclipse-gold font-oswald tracking-widest text-sm flex items-center gap-2">
                                            <ZoomIn size={16} /> AGRANDIR
                                        </span>
                                    </div>
                                </motion.div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Lightbox */}
            <AnimatePresence>
                {lightboxOpen && (
                    <motion.div
                        className="fixed inset-0 z-[60] flex items-center justify-center bg-black/95 backdrop-blur-md"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                    >
                        <button
                            className="absolute top-6 right-6 text-white/50 hover:text-white transition-colors z-50 p-2"
                            onClick={closeLightbox}
                            aria-label="Fermer"
                        >
                            <X size={32} />
                        </button>

                        <button
                            className="absolute left-4 md:left-8 text-white/50 hover:text-eclipse-gold transition-colors z-50 p-2 hidden md:block"
                            onClick={() => navigateLightbox(-1)}
                            aria-label="Précédent"
                        >
                            <ChevronLeft size={48} />
                        </button>

                        <button
                            className="absolute right-4 md:right-8 text-white/50 hover:text-eclipse-gold transition-colors z-50 p-2 hidden md:block"
                            onClick={() => navigateLightbox(1)}
                            aria-label="Suivant"
                        >
                            <ChevronRight size={48} />
                        </button>

                        <motion.div
                            className="relative max-w-7xl w-full h-full flex items-center justify-center p-4 md:p-10"
                            key={lightboxIndex}
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            transition={{ duration: 0.3 }}
                        >
                            <img
                                src={`/assets/gallery/${galleryImages[lightboxIndex].base}.webp`}
                                alt={galleryImages[lightboxIndex].alt}
                                className="max-h-[85vh] max-w-full object-contain shadow-2xl shadow-black/50 rounded-sm"
                                onError={(e) => {
                                    const target = e.currentTarget;
                                    const fallback = `/assets/gallery/${galleryImages[lightboxIndex].base}.jpg`;
                                    if (target.src !== window.location.origin + fallback) {
                                        target.src = fallback;
                                    }
                                }}
                            />
                            <div className="absolute bottom-6 left-0 right-0 text-center">
                                <span className="text-white/60 font-oswald tracking-wider bg-black/50 px-4 py-2 rounded-full backdrop-blur-sm">
                                    {lightboxIndex + 1} / {galleryImages.length}
                                </span>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </section>
    );
};
